# Report all tests as passing, regardless of the coverage
coverage:
    status:
        project:
            default:
                threshold: 100%
                base: parent
        patch:
            default:
                threshold: 100%
                base: parent

# Disable PR comments
comment: false

# Disable annotations
github_checks:
    annotations: false

# Once the coverage has been restored, re-enable the comments and use the
# following flag to report after all tests have been completed (currently 8).
#comment:
#    # This must be set to the number of test cases (TCs)
#    after_n_builds: 8
