# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 solutions.

# This is a not a c-language project but we use the same environment.
language: c
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tcsh pkg-config netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev gfortran
    - doxygen graphviz flex bison cmake

# Compilation and testing is controlled by the "configure" and "Makefile" in
# .testing/ but they operate from the root directory. We copy them into place
# so that they can remain hidden from users.
install:
  - echo "Install step"
  - cp .testing/{configure,Makefile.new} .
  - mv Makefile.new Makefile

jobs:
  include:
    - env: JOB="Code style compliance"
      script:
        - ./.testing/trailer.py -e TEOS10 -l 120 src config_src
    - env: JOB="Doxygen"
      script:
        - cd docs && doxygen Doxyfile_nortd
        - grep -v "config_src/solo_driver/coupler_types.F90" doxygen.log | tee doxy_errors
        - test ! -s  doxy_errors
    - env: JOB="Compile and run"
      script:
        - echo 'Configuring...' && echo -en 'travis_fold:start:script.1\\r'
        - make
        - echo -en 'travis_fold:end:script.1\\r'
        - echo 'Running tests...' && echo -en 'travis_fold:start:script.2\\r'
        - make test
        - echo -en 'travis_fold:end:script.2\\r'
